@startuml
'https://plantuml.com/sequence-diagram
participant Main
participant Client
participant Intermediate
participant Server

autonumber

== Setup ==
Main -> Server ++: run
Main -> Intermediate ++: run
Main -> Client ++: run

Client -> Client:

@enduml